[CI] add summary job for light CI

diff --git a/.github/workflows/on_pr.yml b/.github/workflows/on_pr.yml
--- a/.github/workflows/on_pr.yml
+++ b/.github/workflows/on_pr.yml
@@ -51,3 +51,18 @@ jobs:
         else
           exit 0
         fi
+
+  all_light:
+    needs: [ main_workflow ]
+    # run always except for cancel
+    if: ${{ always() && !cancelled() && contains(github.event.pull_request.labels.*.name, 'light-ci') }}
+    runs-on: ubuntu-latest
+    steps:
+    - name: Status summary
+      run: |
+        if [ "${{ needs.main_workflow.result }}" == "failure" ] || [ "${{ needs.main_workflow.result }}" == "canceled" ]; then
+          echo "Tests failed."
+          exit 1
+        else
+          exit 0
+        fi
